<a href="https://colab.research.google.com/github/Partha-deuri/learn_pytorch/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
2+2

4

In [2]:
import torch

In [4]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
aiohttp                          3.9.5
aiosignal                        1.3.1
alabaster                        0.7.16
albumentations                   1.3.1
altair                           4.2.2
annotated-types                  0.7.0
anyio                            3.7.1
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array_record                     0.5.1
arviz                            0.15.1
astropy                          5.3.4
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.1.0
attrs                            23.2.0
audioread                        3.0.1
autograd                         1.6.2
Babel                            2.15.0
backcall                         0.2.0
beautifulsoup4                   4.12.3
bidict                           0.23.1

# **List**

In [5]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

# Numpy array

In [6]:
import numpy as np

In [7]:
np1 = np.random.rand(3,4)
np1

array([[0.96712716, 0.84243926, 0.9913268 , 0.69455757],
       [0.66526863, 0.2214244 , 0.90292258, 0.27506737],
       [0.06689471, 0.90454872, 0.88650386, 0.03700864]])

In [9]:
np1.dtype

dtype('float64')

# **Tensor**

In [10]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-0.8022,  2.0079,  1.3188,  0.8372],
        [-0.0542,  0.6941,  0.8076,  0.2809],
        [ 1.4559, -0.0022,  0.0111, -0.2301]])

In [11]:
tensor_2d.dtype

torch.float32

In [12]:
tensor_3d = torch.zeros(3,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

#Create tensor from numpy array

In [13]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.9671, 0.8424, 0.9913, 0.6946],
        [0.6653, 0.2214, 0.9029, 0.2751],
        [0.0669, 0.9045, 0.8865, 0.0370]], dtype=torch.float64)

#video 3

#tensor operations

In [14]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
#reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [19]:
my_torch = my_torch.reshape(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# reshape if we don't know the no. of items using  -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
my_torch2 = my_torch2.reshape(-1,2)
my_torch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [27]:
#view

my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [29]:
#with reshape and  view they will update
my_torch5 =  torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [31]:
my_torch5[1] = 123
my_torch5

tensor([  0, 123,   2,   3,   4,   5,   6,   7,   8,   9])

In [32]:
my_torch6

tensor([[  0, 123,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [34]:
#slices

my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
my_torch7[8]=123
my_torch7[8]

tensor(123)

In [40]:
#grabe a slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[  0,   1],
        [  2,   3],
        [  4,   5],
        [  6,   7],
        [123,   9]])

In [41]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [42]:
#return colomn
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

#video 4

#Math operation

In [43]:
import torch
import numpy as np

In [44]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])


In [45]:
#addition short hand
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [46]:
# addition long hand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [47]:
#subraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [49]:
#sub function
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [50]:
#mulitipication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [51]:
# mul func
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [53]:
#div
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [54]:
#div func
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [55]:
#remainder
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [56]:
#remainder func
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [58]:
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [57]:
#exponent /power
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [59]:
#reassignment_
tensor_a

tensor([1, 2, 3, 4])

In [61]:
tensor_a.add_(tensor_b)
#tensor_a = tensor_a + tensor_b

tensor([11, 14, 17, 20])

In [64]:
tensor_a.sub_(tensor_b)

tensor([1, 2, 3, 4])

In [65]:
tensor_a

tensor([1, 2, 3, 4])

#video 5

#Basic NN